CREATE USER WEBMASTER IDENTIFIED BY webmaster DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp PROFILE DEFAULT;

GRANT CREATE VIEW, CREATE SYNONYM TO WEBMASTER;

GRANT CONNECT, RESOURCE TO WEBMASTER;

GRANT UNLIMITED TABLESPACE TO WEBMASTER;

ALTER USER WEBMASTER ACCOUNT UNLOCK;